//! `Daedalus` is an experimental open-source micro bootloader for
//! the LionsOS system developed ontop of seL4.
//!
//! Check out the [repository README](https://github.com/duplessisaurore/daedalus/blob/main/README.md)
//! for more information.
//!
//! ## Daedalus Service
//!
//! The `daedalus_program` crate provides a library combined with a build
//! script that embeds daedalus programs into the bootloader binary as pre-parsed
//! and validated rust structs.

#![feature(const_cmp)]
#![feature(const_trait_impl)]
#![no_std]

use core::fmt::Display;

use lepton3::lepton_image::{
    flags::ImageFlags,
    format::{Function, Header, ObjectType},
    image_trait::{LeptonImage, LeptonSourceLocation},
};

/// A static source location with a static context
/// that can be embedded as a struct literal easily
#[derive(Debug)]
pub struct StaticSourceLocation {
    pub instruction_offset: u32,
    pub file: u32,
    pub line: u32,
    pub column: u32,
    pub context: &'static str,
}

pub trait StaticLeptonImage: LeptonImage<StaticSourceLocation, File = &'static str> {}

/// One Lepton3 daedalus program
pub struct Program<Image: StaticLeptonImage + 'static> {
    /// The name of the program, this is defined in the
    /// "name" field of the manifest.toml
    pub name: &'static str,

    /// The actual image (lepton3) of this program
    pub image: &'static Image,

    /// Grants to this program, these are static
    /// memory regions this program should have
    /// access to by default on creation
    pub grants: &'static [Grant],

    /// The interrupts assigned to this process.
    /// 
    /// These are static assignments from the manifest
    pub interrupts: &'static [Interrupt]
}

/// One Lepton3 daedalus phase
pub struct Phase<Image: StaticLeptonImage + 'static> {
    /// The program this phase is running
    pub program: &'static Program<Image>,

    /// The name of the phase
    pub name: &'static str,

    /// The name of the next phase to run on success.
    pub next: &'static str,
}

/// A grant of memory which is essentially just
/// a statically defined region granted to a program
pub struct Grant {
    /// The "role" of this region, which is how programs
    /// get the region at runtime
    pub role: &'static str,

    // Same as `Region`.
    pub base: GrantBase,
    pub len: GrantLen,
    pub perms: RegionPermissions,
    pub kind: RegionMemKind,
}

// This is generated by the build script for all of our included programs :D
// from the daedalus program manifests
include!(concat!(env!("OUT_DIR"), "/programs.rs"));

impl LeptonSourceLocation for StaticSourceLocation {
    type Context = &'static str;

    fn instruction_offset(&self) -> u32 {
        self.instruction_offset
    }

    fn file(&self) -> u32 {
        self.file
    }

    fn line(&self) -> u32 {
        self.line
    }

    fn column(&self) -> u32 {
        self.column
    }

    fn context(&self) -> &Self::Context {
        &self.context
    }
}

/// Permissions holdable by a region
///
/// R = bit 1
/// W = bit 2
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct RegionPermissions(u8);

/// These permissison bits for memory regions were attempted to be
/// set but they do not currently exist
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct InvalidRegionPermissionBitsError(pub u64);

impl RegionPermissions {
    /// NO permissions are applicable in this region.
    /// This region has no operations that can be done upon it.
    pub const NONE: Self = RegionPermissions(0b00);

    /// This region is only readable from
    pub const R: Self = RegionPermissions(0b01);

    /// This region is only writable to
    pub const W: Self = RegionPermissions(0b10);

    /// This region can be written to/read from
    pub const RW: Self = RegionPermissions(0b11);

    // All known bits in our permissions, we reject anything
    // not in these known bits.
    const KNOWN: u64 = 0b11;

    /// This interprets the 64 bits provided as a
    /// `Perms` and returns the `Perms` if permitted (as
    /// in the bits are all valid known permission bits)
    pub fn from_bits(bits: u64) -> Result<Self, InvalidRegionPermissionBitsError> {
        if bits & !Self::KNOWN != 0 {
            return Err(InvalidRegionPermissionBitsError(bits));
        }

        Ok(RegionPermissions(bits as u8))
    }

    /// Checks whether or not some `Perms` is
    /// a subset of another sets of `Perms`.
    pub fn contains(self, other: Self) -> bool {
        self.0 & other.0 == other.0
    }
}

/// The kind of memory held
/// in this region.
///
/// Whether or not essentially its normal free
/// memory or device MIMO memory
#[derive(PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Clone, Copy)]
pub enum RegionMemKind {
    /// This memory belongs to normal
    /// RAM/free memory used for storing things
    /// rather than MIMO/Device memory
    Memory,

    /// This is memory belonging to some MIMO
    /// device registers (such as on AARCH64)
    Device,
}

impl Display for RegionPermissions {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let r = if self.contains(Self::R) {
            "READ"
        } else {
            "----"
        };
        let w = if self.contains(Self::W) {
            "WRITE"
        } else {
            "-----"
        };
        write!(f, "{} {}", r, w)
    }
}

/// The base address/location of a statically
/// granted region
pub enum GrantBase {
    /// An absolute address in memory, etc. 0x67
    Absolute(usize),

    /// This grant begins just after Daedalus's memory.
    AfterDaedalus,
}

/// The length of a statically
/// granted region
pub enum GrantLen {
    /// This grant extends to the start of Daedalus's memory
    ToStartDaedalus,

    /// This grant has some bytes length
    Bytes(usize),

    /// This grant extends to the end of DRAM
    ToEndOfMemory,
}

/// This is the priority level of an interrupt
/// 
/// This is a normalised scale from 
/// 
/// 0 - Most urgent
/// 255 - Least urgent
/// 
/// The specific interrupt arch should map this
/// to their own corresponding priority system.
/// 
/// The granularity may also not be portable (as
/// in there may not be 255 uniq levels), in that
/// case simply chunk the normalised priority into
/// the actual number of priority levels.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug)]
pub struct InterruptPriority(pub u8);

/// One interrupt that is assigned to this process.
pub struct Interrupt {
    /// The unique ID of this interrupt on hardware.
    /// 
    /// This must be the *actual* interrupt id.
    pub id: u32,

    /// The trigger type of the interrupt.
    /// 
    /// This determines how the interrupt is maintained active wise.
    pub trigger: InterruptTrigger,

   /// How urgent this interrupt is relative to others.
   /// 
   /// See `InterruptPriority`
    pub priority: InterruptPriority,
}

/// The trigger type of an interrupt
/// 
/// This defines how its activated
pub enum InterruptTrigger {
    /// This signal is maintained until serviced by the user
    Level,

    /// This signal is a momentary pulse
    Edge,
}