//! `Daedalus` is an experimental open-source micro bootloader for
//! the LionsOS system developed ontop of seL4.
//!
//! Check out the [repository README](https://github.com/duplessisaurore/daedalus/blob/main/README.md)
//! for more information.
//!
//! ## Daedalus Service
//!
//! The `daedalus_program` crate provides a library combined with a build
//! script that embeds daedalus programs into the bootloader binary as pre-parsed
//! and validated rust structs.

#![feature(const_cmp)]
#![feature(const_trait_impl)]
#![no_std]

use lepton3::lepton_image::{
    flags::ImageFlags,
    format::{Function, Header, ObjectType},
    image_trait::{LeptonImage, LeptonSourceLocation},
};

/// A static source location with a static context
/// that can be embedded as a struct literal easily
#[derive(Debug)]
pub struct StaticSourceLocation {
    pub instruction_offset: u32,
    pub file: u32,
    pub line: u32,
    pub column: u32,
    pub context: &'static str,
}

pub trait StaticLeptonImage: LeptonImage<StaticSourceLocation, File = &'static str> {}

/// One Lepton3 daedalus program
pub struct Program<Image: StaticLeptonImage + 'static> {
    // The name of the program, this is defined in the
    // "name" field of the manifest.toml
    pub name: &'static str,

    // The actual image (lepton3) of this program
    pub image: &'static Image,
}

/// One Lepton3 daedalus phase
pub struct Phase<Image: StaticLeptonImage + 'static> {
    // The program this phase is running
    pub program: &'static Program<Image>,

    // The name of the phase
    pub name: &'static str,

    // The name of the next phase to run on success.
    pub next: &'static str,
}

// This is generated by the build script for all of our included programs :D
// from the daedalus program manifests
include!(concat!(env!("OUT_DIR"), "/programs.rs"));

impl LeptonSourceLocation for StaticSourceLocation {
    type Context = &'static str;

    fn instruction_offset(&self) -> u32 {
        self.instruction_offset
    }

    fn file(&self) -> u32 {
        self.file
    }

    fn line(&self) -> u32 {
        self.line
    }

    fn column(&self) -> u32 {
        self.column
    }

    fn context(&self) -> &Self::Context {
        &self.context
    }
}
