//! `Daedalus` is an experimental open-source micro bootloader for
//! the LionsOS system developed ontop of seL4.
//!
//! Check out the [repository README](https://github.com/duplessisaurore/daedalus/blob/main/README.md)
//! for more information.
//!
//! ## Daedalus Service
//!
//! The `daedalus_service` crate provides a library combined with a build
//! script that embeds daedalus programs into a slice of `Programs` provided
//! to the bootloader

#![feature(const_cmp)]
#![feature(const_trait_impl)]
#![no_std]

/// One Lepton3 daedalus program
pub struct Program {
    // The name of the program, this is defined in the
    // "name" field of the manifest.toml
    pub name: &'static str,

    // These are the services this program provides
    pub services: &'static [&'static str],

    // These are the services this program requires to run
    pub requires: &'static [&'static str],

    // The actual image bytes (lepton3) of this program
    pub image: &'static [u8],
}

/// One Lepton3 daedalus phase
pub struct Phase {
    // The program this phase is running
    pub program: &'static Program,

    // The name of the phase
    pub name: &'static str,

    // The name of the next phase to run on success.
    pub next: &'static str,
}

// This is generated by the build script for all of our included programs :D
// from the daedalus program manifests
include!(concat!(env!("OUT_DIR"), "/programs.rs"));

/// Returns all the programs loaded into this image
pub const fn all() -> &'static [Program] {
    PROGRAMS
}
