[package]
name = "daedalus"
version = "1.0.0"
edition = "2024"
authors = ["The Daedalus Contributors"]

description = "A services-oriented micro-bootloader built on the Lepton3 virtual machine."
readme = "README.md"

repository = "https://github.com/duplessisaurore/daedalus"
license = "AGPLv3"

keywords = ["languages", "scripting", "script"]

[dependencies]
linked_list_allocator = { workspace = true }
cfg-if = { workspace = true }
lepton3 = { workspace = true }
daedalus_caps = { workspace = true }
daedalus_program = { workspace = true }

[features]
# Panic debug, read very carefully before enabling!
panic-debug = []

# Supported platforms

# Xilinx
platform-zynqmp = ["daedalus_caps/platform-zynqmp"]
platform-zcu106 = ["daedalus_caps/platform-zcu106", "platform-zynqmp"]
